package com.techyourchance.coroutines.home

enum class ScreenReachableFromHome(val description: String) {
    UI_THREAD_DEMO("UI Thread"),
    BACKGROUND_THREAD_DEMO("Background Thread"),
    BASIC_COROUTINES_DEMO("Basic Coroutines"),
    EXERCISE_1("Exercise 1"),
    COROUTINES_CANCELLATION_DEMO("Coroutines Cancellation"),
    EXERCISE_2("Exercise 2"),
    CONCURRENT_COROUTINES_DEMO("Concurrent Coroutines"),
    SCOPE_CHILDREN_CANCELLATION_DEMO("Scope Children Cancellation"),
    EXERCISE_3("Exercise 3"),
    SCOPE_CANCELLATION_DEMO("Scope Cancellation"),
    VIEWMODEL_DEMO("ViewModel"),
    EXERCISE_4("Exercise 4"),
    DESIGN_DEMO("Design Demo"),
    EXERCISE_5("Exercise 5"),
    COROUTINES_CANCELLATION_COOPERATIVE_DEMO("Coroutines Cancellation Cooperative"),
    COROUTINES_CANCELLATION_COOPERATIVE_2_DEMO("Coroutines Cancellation Cooperative 2"),
    EXERCISE_6("Exercise 6"),
    NON_CANCELLABLE_DEMO("Non-Cancellable"),
    EXERCISE_8("Exercise 8"),
    EXERCISE_9("Exercise 9"),
    UNCAUGHT_EXCEPTION_DEMO("Uncaught Exception"),
    EXERCISE_10("Exercise 10"),
}