name: CI checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  AndroidLints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          clean: 'false'
      - name: Gradle
        uses: gradle/gradle-build-action@v2.1.5

      - name: Run Build
        run: ./gradlew assembleDebug
